apiVersion: v1
kind: Pod
metadata:
  name: my-secret-pod
spec:
  containers:
  - name: my-secret-pod
    image: pymonger/calrissian:latest
    imagePullPolicy: IfNotPresent
    tty: true
    stdin: true
    command: ["/bin/bash", "-ec", "while :; do echo '.'; sleep 15 ; done"]
    volumeMounts:
    - name: my-volume
      mountPath: "/home/calrissian/.aws"
      readOnly: true
  volumes:
  - name: my-volume
    secret:
      secretName: aws-creds
